language: node_js
node_js:
  - "4"
  - "7"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  skip_cleanup: true
  - provider: script
    script: run npm deploy
    on:
        branch: master
